export const transactions = [
  { id: 1, name: "Netflix", description: "Month subscription", price: "$12" },
  { id: 2, name: "Spotify", description: "Music streaming", price: "$10" },
  { id: 3, name: "Uber", description: "Ride", price: "$15" },
  { id: 4, name: "iFood", description: "Food delivery", price: "$30" },
  {
    id: 5,
    name: "Mercado Livre",
    description: "Online shopping",
    price: "$50",
  },
  { id: 6, name: "Gym membership", description: "Monthly fee", price: "$80" },
  { id: 7, name: "Restaurant", description: "Dinner", price: "$70" },
  { id: 8, name: "Movie tickets", description: "Cinema", price: "$40" },
  { id: 9, name: "Concert tickets", description: "Live music", price: "$120" },
  { id: 10, name: "Travel", description: "Flight", price: "$300" },
  { id: 11, name: "Electricity bill", description: "Utilities", price: "$80" },
  { id: 12, name: "Water bill", description: "Utilities", price: "$40" },
  { id: 13, name: "Phone bill", description: "Utilities", price: "$60" },
  { id: 14, name: "Internet bill", description: "Utilities", price: "$70" },
  { id: 15, name: "Groceries", description: "Supermarket", price: "$100" },
  { id: 16, name: "Coffee shop", description: "Drinks", price: "$5" },
  { id: 17, name: "Haircut", description: "Personal care", price: "$30" },
  { id: 18, name: "Clothing", description: "Shopping", price: "$60" },
  { id: 19, name: "Gift", description: "Present", price: "$20" },
  { id: 20, name: "Taxi", description: "Transportation", price: "$20" },
];
